### ISSUE TITLE
Project does not work with core's 10.0.x branch

### ISSUE THREAD

**Issue by andy-blum** [joachim-n/drupal-core-development-project#11]
Installed per the instructions in the readme, and then switched to the 10.0.x branch. Kicked off a DDEV project with it and the project errors with:

> Warning: require(/var/www/html/vendor/composer/../../web/core/includes/guzzle_php81_shim.php): Failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 75

> Fatal error: Uncaught Error: Failed opening required '/var/www/html/vendor/composer/../../web/core/includes/guzzle_php81_shim.php' (include_path='/var/www/html/vendor/pear/pear_exception:/var/www/html/vendor/pear/console_getopt:/var/www/html/vendor/pear/pear-core-minimal/src:/var/www/html/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php:75 Stack trace: #0 /var/www/html/vendor/composer/autoload_real.php(65): composerRequirebe8a091bca0079a3222cb044f9050d36('6db5533840cb1ae...', '/var/www/html/v...') #1 /var/www/html/vendor/autoload.php(7): ComposerAutoloaderInitbe8a091bca0079a3222cb044f9050d36::getLoader() #2 /var/www/html/repos/drupal/autoload.php(14): require('/var/www/html/v...') #3 /var/www/html/repos/drupal/core/install.php(38): require_once('/var/www/html/r...') #4 {main} thrown in /var/www/html/vendor/composer/autoload_real.php on line 75

**Comment by rfay** [comment]
Was this with php8.1 or what version? Did you update composer after changing branches?

**Comment by andy-blum** [comment]
Oh, I misunderstood how this was going to work. After `composer create-project` and switching the repo to 10.0.x, re-runming `composer install` within the DDEV web container got me to the install UI. Closing this issue - will re-open if other issue arise.
