### ISSUE TITLE
DevelopmentProjectCommands Class conflicts for Drush 12

### ISSUE THREAD

**Issue by bhanu951** [joachim-n/drupal-core-development-project#19]
`DevelopmentProjectCommands` Class conflicts for Drush 12+ and produces below error when running any `drush` commands.
```

drush st
PHP Fatal error:  Class Drush\Commands\core_development\DevelopmentProjectCommands cannot extend final class Drush\Commands\core\CacheCommands in /var/www/html/drush/Commands/core_development/DevelopmentProjectCommands.php on line 0

Fatal error: Class Drush\Commands\core_development\DevelopmentProjectCommands cannot extend final class Drush\Commands\core\CacheCommands in /var/www/html/drush/Commands/core_development/DevelopmentProjectCommands.php on line 0
 [warning] Drush command terminated abnormally.
```
Current [CacheCommands](https://github.com/drush-ops/drush/blob/12.x/src/Commands/core/CacheCommands.php#L30) class is final in Drush Version 12+ Introduced in PR https://github.com/drush-ops/drush/pull/5427

**Comment by weitzman** [comment]
You can use the replace hook to use your own method instead of the one provided by CacheCommands https://github.com/consolidation/annotated-command#replace-command-hook

**Comment by joachim-n** [comment]
Fixed!

Thanks for reporting @bhanu951.

New release coming.
