### ISSUE TITLE
Install command results in error

### ISSUE THREAD

**Issue by pyrello** [joachim-n/drupal-core-development-project#22]
Running the `composer create-project` command from https://github.com/joachim-n/drupal-core-development-project#installation results in the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drupal/core-recommended * -> satisfiable by drupal/core-recommended[11.x-dev].
    - drupal/core-recommended 11.x-dev requires drupal/core 10.2.x-dev -> found drupal/core[11.x-dev] but it does not match the constraint.
```

I had previously installed this project with no issues and was in the process of re-installing after removing the previous installation.

**Comment by pyrello** [comment]
Possibly related: https://www.drupal.org/project/drupal/issues/3364646

**Comment by joachim-n** [comment]
If you switch the core repo to 10.2.x, can you then do `composer install`?

**Comment by pyrello** [comment]
This is what I got:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drupal/core 10.2.x, found drupal/core[11.x-dev] but it does not match the constraint.
  Problem 2
    - Root composer.json requires drupal/drupal * -> satisfiable by drupal/drupal[11.x-dev].
    - drupal/drupal 11.x-dev requires drupal/core 11.x-dev -> found drupal/core[11.x-dev] but it conflicts with your root composer.json require (10.2.x).
  Problem 3
    - Root composer.json requires drupal/core-recommended * -> satisfiable by drupal/core-recommended[11.x-dev].
    - drupal/core-recommended 11.x-dev requires drupal/core 10.2.x-dev -> found drupal/core[11.x-dev] but it does not match the constraint.
```

**Comment by joachim-n** [comment]
Hmmm. I think we need to set up branch aliases in Composer somehow. Can you try changing the root composer to say:

```
"drupal/core": "11.x as 10.2.x-dev",
```

**Comment by pyrello** [comment]
I was able to work around it for the meantime by just removing `"drupal/core-recommended": "*"` from the root composer.json file.

I tested out your suggestion and it appears to work.

**Comment by joachim-n** [comment]
I tried `ddev composer create-project joachim-n/drupal-core-development-project` and I got:

```
'ddev composer create-project' is unsupported. Please use 'ddev composer create'
for basic project creation or 'ddev ssh' into the web container and execute
'composer create-project' directly.
```

**Comment by jameswilson** [comment]
My apologies. That was an incorrect copy paste. This is the command:

```
ddev composer create joachim-n/drupal-core-development-project
```

**Comment by joachim-n** [comment]
That's working for me too.

That's great news that it works now!!! Thanks for reporting!

I'll update the README.
