### ISSUE TITLE
DRUPAL_ROOT value is the symlinked directory, instead of the project location

### ISSUE THREAD

**Issue by shaal** [joachim-n/drupal-core-development-project#8]
## Describe the bug

When installing a Drupal website that is based on this project, `DRUPAL_ROOT` gets the wrong value - `/var/www/html/repos/drupal`.

## To Reproduce

1. Install a Drupal website based on this project's setup.
1.  using Xdebug, place a breakpoint in `web/core/includes/bootstrap.inc`, after the line where `DRUPAL_ROOT` gets value
`define('DRUPAL_ROOT', dirname(__DIR__, 2));
`
1. Confirm that DRUPAL_ROOT gets the wrong value of `repos/drupal` instead of the directory where Drupal project is.

## Expected behavior

I expect DRUPAL_ROOT to be set like a regular Drupal website (and not in `/repos/drupal')

**Comment by joachim-n** [comment]
Can this be closed? Isn't this basically https://www.drupal.org/project/drupal/issues/1792310?

**Comment by shaal** [comment]
Yes, it is. Closing.
